spring.application.name=modularArchitecture


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=avanish7080
spring.jpa.hibernate.ddl-auto=update
